### ISSUE TITLE
Add option for INPUT_TYPE=EMOTIONML

### ISSUE THREAD

**Issue by h4de5** [Poeschl/speak2mary#1]
I just found out that you can put emotions into marytts using a INPUT_TYPE=EMOTIONML and now I would like to have my audio have a sad tune:

it seems the styles api does not deliver the available styles:
http://localhost:59125/styles?voice=dfki-pavoque-neutral-hsmm

but from the example/test page you can see that there are different styles available:

e.g.:
http://localhost:59125/process?INPUT_TYPE=EMOTIONML&OUTPUT_TYPE=AUDIO&INPUT_TEXT=%3Cemotionml%20version%3D%221.0%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2009%2F10%2Femotionml%22%20%0Acategory-set%3D%22http%3A%2F%2Fwww.w3.org%2FTR%2Femotion-voc%2Fxml%23everyday-categories%22%3E%3Cemotion%3E%3Ccategory%20name%3D%22sad%22%2F%3EIch%20k%C3%B6nnte%20dir%20deine%20%C3%9Cberlebenschancen%20ausrechnen,%20aber%20du%20w%C3%A4rst%20nicht%20begeistert.%3C%2Femotion%3E%3C%2Femotionml%3E%0A&OUTPUT_TEXT=&AUDIO_OUT=WAVE_FILE&LOCALE=de&VOICE=dfki-pavoque-neutral-hsmm&AUDIO=WAVE_FILE

**Comment by Poeschl** [comment]
So which parameter specify the emotion of the generated sound? And `INPUT_TYPE` needs to be `EMOTIONML`, right?

**Comment by h4de5** [comment]
INPUT_TYPE yes.

The input needs to change to xml and the emotions would be defined there. if the emotion is limited to a single one, the text would just have a pre- and post-template.

```xml
<emotionml version="1.0" xmlns="http://www.w3.org/2009/10/emotionml" 
category-set="http://www.w3.org/TR/emotion-voc/xml#everyday-categories">
Hallo und guten Tag.

<emotion><category name="angry"/>
Was ist das jetzt schon wieder?
</emotion>

<emotion><category name="happy"/>
Schön dich wieder zu sehen.
</emotion>

<emotion><category name="sad"/>
Das hatte ich auch anders im Sinn.
</emotion>

<emotion><category name="content"/>
Na jedenfalls gibt's was Gutes zu sehen.
</emotion>

  <emotion dimension-set="http://www.w3.org/TR/emotion-voc/xml#pad-dimensions">
  Ich bin ruhig.
    <dimension name="arousal" value="0.3"/><!-- lower-than-average arousal -->
    <dimension name="pleasure" value="0.9"/><!-- very high positive valence -->
    <dimension name="dominance" value="0.8"/><!-- relatively high potency    -->
  </emotion>

  <emotion dimension-set="http://www.w3.org/TR/emotion-voc/xml#pad-dimensions">
  Ich bin nervös!
    <dimension name="arousal" value="0.9"/><!-- high arousal -->
    <dimension name="pleasure" value="0.2"/><!-- negative valence -->
    <dimension name="dominance" value="0.2"/><!-- low potency    -->
  </emotion>

</emotionml>
```
